sudo: false

before_script: "npm install --dev"

language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "8"
  - "10"

branches:
  only:
    - master

notifications:
  email:
    - adriano@raiano.ch
